### ISSUE TITLE
ERR Error running script

### ISSUE THREAD

**Issue by coldlamper** [RedisLabs/redis-lua-debugger#4]
i have a test.lua file with only rld.start()
When I run: 
redis-cli --eval test.lua
I get:
(error) ERR Error running script (call to f_e5714a15d43e16e25b40656259d4f1d5028a742f): @enable_strict_lua:15: user_script:218: Script attempted to access unexisting global variable 'debug'

**Comment by mhenrixon** [comment]
:+1:

**Comment by itamarhaber** [comment]
Oops - didn't notice this one, sorry. Will dig into asap!

**Comment by joshng** [comment]
:+1:

**Comment by ferdypruis** [comment]
I am having the same, running redis-cli 3.0.3

When I eval a script with only "redis.log(0, debug)" I have the same;
> (error) ERR Error running script (call to f_d42bc35de2f6bd7ed1801f7fc27eb08006d25a9f): @enable_strict_lua:15: user_script:1: Script attempted to access unexisting global variable 'debug'

Seems the debug lib is not loaded.

**Comment by itamarhaber** [comment]
Sorry all, looks like my hacks no longer work in v3 - https://github.com/antirez/redis/commit/30278061cc834b4073b004cb1a2bfb0f195734f7
